from turtle import *

my_turtle = Turtle()
my_turtle.speed(0)
my_turtle.screen.setup(800, 600)

my_turtle.penup()
my_turtle.goto(0, -50)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("black")
my_turtle.circle(50)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(-60, 10)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("black")
my_turtle.circle(20)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(60, 10)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("black")
my_turtle.circle(20)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(-20, -10)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("white")
my_turtle.circle(10)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(20, -10)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("white")
my_turtle.circle(10)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(0, -30)
my_turtle.pendown()
my_turtle.begin_fill()
my_turtle.color("white")
my_turtle.circle(5)
my_turtle.end_fill()

my_turtle.hideturtle()
my_turtle.screen.exitonclick()